<?php

/**
 * Array of base categories tree.
 */

$bue_en = trans('meta.phrases.bue', [], 'en');
$features_en = trans('meta.phrases.features', [], 'en');
$wholesaleRetail_en = trans('meta.phrases.wholesale_and_retail', [], 'en');
$originalCopy_en = trans('meta.phrases.original_and_copy', [], 'en');

$bue_ru = trans('meta.phrases.bue', [], 'ru');
$features_ru = trans('meta.phrases.features', [], 'ru');
$wholesaleRetail_ru = trans('meta.phrases.wholesale_and_retail', [], 'ru');
$originalCopy_ru = trans('meta.phrases.original_and_copy', [], 'ru');

$bue_ua = trans('meta.phrases.bue', [], 'ua');
$features_ua = trans('meta.phrases.features', [], 'ua');
$wholesaleRetail_ua = trans('meta.phrases.wholesale_and_retail', [], 'ua');
$originalCopy_ua = trans('meta.phrases.original_and_copy', [], 'ua');

return [
    'breadcrumb' => '',
    'url' => '',
    'image' => null,
    'title_en' => 'Spare parts for mobile phones and tablets',
    'title_ru' => 'Запчасти к мобильным телефонам и планшетам',
    'title_ua' => 'Запчастини до мобільних телефонів і планшетів',
    'page_title_en' => 'Spare parts for mobile phones and tablets',
    'page_title_ru' => 'Запчасти к мобильным телефонам и планшетам',
    'page_title_ua' => 'Запчастини до мобільних телефонів і планшетів',
    'meta_title_en' => 'Spare parts for mobile phones and tablets ' . $wholesaleRetail_en,
    'meta_title_ru' => 'Запчасти к мобильным телефонам и планшетам ' . $wholesaleRetail_ru,
    'meta_title_ua' => 'Запчастини до мобільних телефонів і планшетів ' . $wholesaleRetail_ua,
    'meta_description_en' => 'Spare parts ' . $wholesaleRetail_en . ' for mobile phones and tablets of any brands: ' . $features_en . ' &#8212; ' . $bue_en,
    'meta_description_ru' => 'Запчасти ' . $wholesaleRetail_ru . ' к мобильным телефонам и планшетам любых брендов: ' . $features_ru . ' &#8212; ' . $bue_ru,
    'meta_description_ua' => 'Запчастини ' . $wholesaleRetail_ua . ' до мобільних телефонів і планшетів будь-яких брендів: ' . $features_ua . ' &#8212; ' . $bue_ua,
    'meta_keywords_en' => 'spare parts for mobile phones, spare parts for tablets, buy wholesale and retail in Kiev',
    'meta_keywords_ru' => 'запчасти к мобильным телефонам, запчасти к планшетам, купить оптом и в розницу в Киеве',
    'meta_keywords_ua' => 'запчастини до мобільних телефонів, запчастини до планшетів, купити оптом і в роздріб в Києві',
    'summary_en' => '<p>Modern mobile phones and tablets are complex devices consisting of many spare parts. The desire to reduce the thickness of the phone leads to the need to reduce the size of components and increase the density of the layout of parts. This leads to a decrease in the reliability of the device, overheating, rapid failure of the phone parts. Therefore, periodic purchase and replacement of spare parts becomes a necessity even for mobile phones of well-known brands such as Apple or Samsung. </p><p>The increased size of the display helps to damage it when falling and striking. Buying a cover or protective film can solve this problem. Water and dirt entering the microphone, speaker, camera causes the need to replace them. Scratches, abrasions of the case, loose fit of the back cover of the phone - an occasion to replace the case of the device or its back cover.</p><p>Occasionally, the chips fail. For an expensive phone, you will have to buy and solder chips.</p><p>Almost any mobile phone or tablet will have to change the battery, at least, with a limited lifespan. Also sometimes you need to change the cable, charge, buy gadgets: headphones, external batteries. Over time, there may be a desire to increase the size of flash memory.</p><p>These and other spare parts for mobile phones and tablets can be purchased at the ' . config('app.name') . ' store. We work only with proven, carefully selected suppliers of components. All spare parts are checked at the factory before shipment, therefore the percentage of return of the marriage is minimal.</p><p>If you are a service center, then by purchasing wholesale items you will save much. The wholesale price for spare parts and gadgets for phones is much lower. Constant retail customers are also provided with cumulative discounts.</p>',
    'summary_ru' => '<p>Современные мобильные телефоны и планшеты - это сложные устройства состоящие из множества запчастей. Стремление к уменьшению толщины телефона приводит к необходимости уменьшать размеры комплектующих и повышению плотности компоновки деталей. Это приводит к уменьшению надежности работы устройства, перегреву, быстрому выходу из строя деталей телефона. Поэтому периодическая покупка и замена запчастей становится необходимостью даже для мобильных телефонов известных брендов, таких как Apple или Samsung.</p><p>Увеличенный размер дисплея способствует его повреждению при падениях и ударах. Покупка чехла или защитной пленки может решить эту проблему. Попадание воды и грязи в микрофон, динамик, камеру приводит к необходимости их замены. Царапины, потертости корпуса, неплотное прилегание задней крышки телефона - повод заменить корпус аппарата или его заднюю крышку.</p><p>Изредка выходят из строя микросхемы. Для дорогого телефона придется купить и перепаивать чипы.</p><p>Практически в любом мобильном телефоне или планшете хоть раз придется поменять аккумуляторную батарею, срок службы которой ограничен. Также иногда нужно менять кабеля, зарядки, докупать гаджеты: наушники, внешние аккумуляторы. Со временем может возникнуть желание увеличить размер флеш памяти.</p><p>Эти и другие запасные части к мобильным телефонам и планшетам вы можете приобрести в магазине ' . config('app.name') . '. Мы работаем только с проверенными, тщательно отобранными поставщиками комплектующих. Все запчасти проверяются на заводе перед отправкой, поэтому процент возврата брака минимален.</p><p>Если вы являетесь сервисным центром, то покупая детали оптом вы существенно сэкономите. Оптовая цена на запчасти и гаджеты к телефонам существенно ниже. Постоянным розничным клиентам также предоставляются накопительные скидки.</p>',
    'summary_ua' => '<p>Сучасні мобільні телефони та планшети - це складні пристрої що складаються з безлічі запчастин. Прагнення до зменшення товщини телефону призводить до необхідності зменшувати розміри комплектуючих і підвищенню щільності компонування деталей. Це призводить до зменшення надійності роботи пристрою, перегріву, швидкого виходу з ладу його частин. Тому періодична купівля і заміна запчастин стає необхідністю навіть для мобільних телефонів відомих брендів, таких як Apple або Samsung. </p><p>Збільшений розмір дисплея сприяє його пошкодженню при падіннях і ударах. Купівля чохла або захисної плівки може вирішити цю проблему. Попадання води і бруду в мікрофон, динамік, камеру призводить до необхідності їх заміни. Подряпини, потертості корпусу, нещільне прилягання задньої кришки телефону - привід замінити корпус апарату або його задню кришку.</p><p>Зрідка виходять з ладу мікросхеми. Для дорогого телефону доведеться купити чіпи.</p><p>Практично в будь-якому мобільному телефоні або планшеті хоч раз доведеться поміняти акумуляторну батарею, термін служби якої обмежений. Також іноді потрібно міняти кабелі, зарядки, докуповувати гаджети: навушники, зовнішні акумулятори. Згодом може виникнути бажання збільшити розмір флеш пам\'яті.</p><p>Ці та інші запасні частини до мобільних телефонів і планшетів ви можете придбати в магазині ' . config('app.name') . '. Ми працюємо тільки з перевіреними, ретельно відібраними постачальниками комплектуючих. Всі запчастини перевіряються на заводі перед відправкою, тому відсоток повернення браку мінімальний.</p><p>Якщо ви є сервісним центром, то купуючи деталі оптом ви істотно заощадите. Оптова ціна на запчастини і гаджети до телефонів істотно нижче. Постійним роздрібним клієнтам також надаються накопичувальні знижки.</p>',

    'children' => [
        [
            'url' => 'screens',
            'breadcrumb' => 'screens',
            'image' => 'screens.png',
            'title_en' => 'Screens',
            'title_ru' => 'Дисплеи',
            'title_ua' => 'Дисплеї',
            'page_title_en' => 'Displays and touch screens for smartphones and tablets',
            'page_title_ru' => 'Дисплеи и сенсорные экраны к смартфонам и планшетам',
            'page_title_ua' => 'Дисплеї та сенсорні екрани до смартфонів і планшетів',
            'meta_title_en' => 'Displays, touchscreens for smartphones and tablets ' . $wholesaleRetail_en,
            'meta_title_ru' => 'Дисплеи, сенсорные экраны для смартфонов и планшетов ' . $wholesaleRetail_ru,
            'meta_title_ua' => 'Дисплеї, сенсорні екрани для смартфонів і планшетів ' . $wholesaleRetail_ua,
            'meta_description_en' => 'Displays and touch screens ' . $wholesaleRetail_en . ' for smartphones and tablets of any brands: ' . $features_en . ' &#8212; ' . $bue_en,
            'meta_description_ru' => 'Дисплеи и сенсорные экраны ' . $wholesaleRetail_ru . ' для смартфонов и планшетов любых брендов: ' . $features_ru . ' &#8212; ' . $bue_ru,
            'meta_description_ua' => 'Дисплеї і сенсорні екрани ' . $wholesaleRetail_ua . ' для смартфонів і планшетів будь-яких брендів: ' . $features_ua . ' &#8212; ' . $bue_ua,
            'meta_keywords_en' => 'Displays for smartphones and tablets, touch screens for smartphones and tablets, buy wholesale and retail in Kiev',
            'meta_keywords_ru' => 'Дисплеи для смартфонов и планшетов, сенсорные экраны для смартфонов и планшетов, купить оптом и в розницу в Киеве',
            'meta_keywords_ua' => 'Дисплеї для смартфонів і планшетів, сенсорні екрани для смартфонів і планшетів, купити оптом і в роздріб в Києві',
            'summary_en' => '<p>The display (touch screen) in a modern smartphone is the main node for interaction with the user. It serves to output visual information and to enter data at the same time. Therefore, his choice should be approached with special care. There are several types of modern displays:</p><ul><li><strong>TFT screens </strong>is obsolete technology. Disadvantages: the need for backlighting, limited contrast.</li><li><strong>OLED screens </strong>do not need backlighting. They have natural black color of image and they are thinner.</li><li><strong>SuperAMOLED screens &mdash; </strong>are the thinnest, they have build-in sensor.</li></ul><p>Possible problems of touch screens exploitation:</p><ul><li>Wiping, cracking or complete destruction of the protective glass or display.</li><li>Ingress of water.</li><li>Screen burn. This is usually considered a factory defect and does not depend on the operating conditions.</li></ul><p>In our store you can buy wholesale and retail modern high quality displays for smartphones and tablets of all famous brands. All of our displays are 100% tested by the manufacturer, the amount of defective screens is minimal.</p>',
            'summary_ru' => '<p>Дисплей (сенсорный экран) в современном смартфоне является основным узлом для взаимодействия с пользователем. Он служит одновременно для вывода визуальной информации и для ввода данных. Поэтому к его выбору нужно подходить с особой тщательностью. Существует несколько типов современных дисплеев:</p><ul><li><strong>TFT экраны &mdash; </strong>устаревшая технология. Недостатки: необходимость подсветки, ограниченная контрастность.</li><li><strong>OLED экраны &mdash; </strong>отсутствие подсветки, натуральный черный цвет, уменьшенная толщина.</li><li><strong>SuperAMOLED экраны &mdash; </strong>самый тонкий, сенсор встроен в дисплей.</li></ul><p>Возможные проблемы при эксплуатации сенсорных экранов:</p><ul><li>Потертости, трещины или полное разрушение защитного стекла либо дисплея.</li><li>Попадание влаги внутрь</li><li>&laquo;Выгорание&raquo; экрана. Обычно это считается заводским браком и не зависит от условий эксплуатации.</li></ul><p>В нашем магазине вы можете приобрести оптом и в розницу современные дисплеи высокого качества для смартфонов и планшетов всех известных торговых марок. Все наши дисплеи проходят 100% проверку у производителя, количество брака минимально.</p>',
            'summary_ua' => '<p>Дисплей (сенсорний екран) в сучасному смартфоні є основним вузлом для взаємодії з користувачем. Він служить одночасно для виведення візуальної інформації і для введення даних. Тому до його вибору потрібно підходити з особливою ретельністю. Існує кілька типів сучасних дисплеїв: </p><ul><li><strong>TFT екрани &mdash; </strong> застаріла технологія. Недоліки: необхідність підсвічування, обмежена контрастність.</li><li><strong>OLED екрани &mdash; </strong>відсутність підсвічування, натуральний чорний колір, зменшена товщина. </li><li><strong>SuperAMOLED екрани &mdash; </strong>найтонший, сенсор вбудований в дисплей. </li></ul> <p>Можливі проблеми при експлуатації сенсорних екранів:</p><ul><li>Потертості, тріщини або повне руйнування захисного скла або дисплея . </li><li>Попадання вологи всередину.</li><li>&laquo;Вигорання&raquo; екрану. Зазвичай це вважається заводським браком і не залежить від умов експлуатації. </li></ul><p>В нашому магазині ви можете придбати оптом і в роздріб сучасні дисплеї високої якості для смартфонів і планшетів всіх відомих торгових марок. Всі наші дисплеї проходять 100% перевірку у виробника, кількість браку мінімальна.</p>',
        ],
        [
            'url' => 'touchscreens',
            'breadcrumb' => 'touchscreens',
            'image' => 'touchscreens.png',
            'title_en' => 'Touchscreens',
            'title_ru' => 'Тачскрины',
            'title_ua' => 'Тачскріни',
            'page_title_en' => 'Touch screens and sensors for smartphones and tablets',
            'page_title_ru' => 'Тачскрины и сенсоры к смартфонам и планшетам',
            'page_title_ua' => 'Тачскріни та сенсори до смартфонів і планшетів',
            'meta_title_en' => 'Touch screens and sensors for smartphones and tablets ' . $wholesaleRetail_en,
            'meta_title_ru' => 'Тачскрины и сенсоры к смартфонам и планшетам ' . $wholesaleRetail_ru,
            'meta_title_ua' => 'Тачскріни та сенсори до смартфонів і планшетів ' . $wholesaleRetail_ua,
            'meta_description_en' => 'Touch screens and sensors ' . $wholesaleRetail_en . ' for smartphones and tablets of any brands:
' . $features_en . ' &#8212; ' . $bue_en,
            'meta_description_ru' => 'Тачскрины и сенсоры ' . $wholesaleRetail_ru . ' для смартфонов и планшетов любых брендов: ' . $features_ru . ' &#8212; ' . $bue_ru,
            'meta_description_ua' => 'Тачскріни та сенсори ' . $wholesaleRetail_ua . ' для смартфонів і планшетів будь-яких брендів: ' . $features_ua . ' &#8212; ' . $bue_ua,
            'meta_keywords_en' => 'Touch screens for smartphones and tablets, sensors for smartphones and tablets, buy wholesale and retail in Kiev',
            'meta_keywords_ru' => 'Тачскрины для смартфонов и планшетов, сенсоры для смартфонов и планшетов, купить оптом и в розницу в Киеве',
            'meta_keywords_ua' => 'Тачскріни для смартфонів і планшетів, сенсори для смартфонів і планшетів, купити оптом і в роздріб в Києві',
            'summary_en' => '<p>Touchscreen in a modern smartphone and tablet is designed to process tactile information. The sensor responds to the touch of the user, and transmits the calculated touch coordinates.</p><p>The touch screen is subjected to constant mechanical action both from the user\'s side and from accidental falls. The protective film, pasted on the touchscreen, partly helps protect it. However, damage to the screen sensor is the most frequent breakdown of the mobile phone.</p><p>There are 3 types of sensors for mobile devices:</p><ul><li>Resistive</li><li>Capacitive</li><li>Wave</li></ul><p>Usually there is a capacitive touchscreen type. When choosing a touch screen, you must take into account its resolving power.</p><p>In the ' . config('app.name') . ' store you can purchase touchscreens or displays with a sensor assembly for smartphones and tablets of any modern models. Particular attention in the purchase of sensors, we give their quality. Buying touchscreen from us, you can be sure of its reliability. We draw the attention of regular customers and service centers to the fact that to buy touchscreens in bulk is much more profitable. If you supply a wholesale batch of sensors under the order, the prices will be minimal.</p>',
            'summary_ru' => '<p>Тачскрин в современном смартфоне и планшете предназначен для обработки тактильной информации. Сенсор реагирует на прикосновение пользователя, и передает вычисленные координаты нажатия.</p><p>Сенсорный экран подвергается постоянному механическому воздействию как со стороны пользователя, так и при случайных падениях. Защитная пленка, наклеенная на тачскрин отчасти помогает защитить его. Тем не менее повреждение сенсора экрана - наиболее частая поломка мобильного телефона.</p><p>Существует 3 типа сенсоров для мобильных устройств:</p><ul><li>Резистивные</li><li>Емкостные</li><li>Волновой</li></ul><p>Обычно встречается емкостной тип тачскрина. При выборе сенсорного экрана надо учитывать его разрешаюшую способность.</p><p>В магазине ' . config('app.name') . ' вы можете приобрести тачскрины или дисплеи с сенсором в сборе для смартфонов и планшетов любых современных моделей. Особое внимание при закупке сенсоров, мы уделяем их качеству. Покупая тачскрин у нас, вы можете быть уверены в его надежности. Обращаем внимание постоянных покупателей и сервисных центров на то, что купить тачскрины оптом значительно выгодней. При поставке оптовой партии сенсоров под заказ цены будут минимальные.</p>',
            'summary_ua' => '<p>Тачскрін в сучасному смартфоні і планшеті призначений для обробки тактильної інформації. Сенсор реагує на дотик користувача, і передає обчислені координати натискання.</p><p>Сенсорний екран піддається постійному механічному впливу як з боку користувача, так і при випадкових падіннях. Захисна плівка, наклеєна на тачскрін частково допомагає захистити його. Проте пошкодження сенсора екрану - найбільш часта поломка мобільного телефону.</p><p>Існує 3 типи сенсорів для мобільних пристроїв:</p><ul><li>Резистивні</li><li>Ємнісні</li><li>Хвильові</li></ul><p>Зазвичай зустрічається ємнісний тип тачскріну. При виборі сенсорного екрану треба враховувати його роздільну здатність.</p><p>В магазині ' . config('app.name') . ' ви можете придбати тачскрін або дисплеї з сенсором в зборі для смартфонів і планшетів будь-яких сучасних моделей. Особливу увагу під час закупівлі сенсорів, ми приділяємо їх якості. Купуючи тачскрін у нас, ви можете бути впевнені в його надійності. Звертаємо увагу постійних покупців і сервісних центрів на те, що купити тачскрін оптом значно вигідніше. При поставці оптової партії сенсорів під замовлення ціни будуть мінімальні.</p>',
        ],
        [
            'url' => 'case',
            'breadcrumb' => 'case',
            'image' => 'case.png',
            'title_en' => 'Case parts',
            'title_ru' => 'Детали корпуса',
            'title_ua' => 'Деталі корпуса',
            'page_title_en' => 'Carcase and parts of the case for smartphones and tablets',
            'page_title_ru' => 'Корпуса и детали корпуса к смартфонам и планшетам',
            'page_title_ua' => 'Корпуса та деталі корпуса до смартфонів і планшетів',
            'meta_title_en' => 'Carcase | Carcase parts for smartphones and tablets ' . $wholesaleRetail_en,
            'meta_title_ru' => 'Корпуса | Детали корпуса к смартфонам и планшетам ' . $wholesaleRetail_ru,
            'meta_title_ua' => 'Корпуса | Деталі корпуса до смартфонів і планшетів ' . $wholesaleRetail_ua,
            'meta_description_en' => 'Carcase and parts of the case ' . $wholesaleRetail_en . ' for smartphones and tablets of any brands:
' . $features_en . ' &#8212; ' . $bue_en,
            'meta_description_ru' => 'Корпуса и детали корпуса ' . $wholesaleRetail_ru . ' для смартфонов и планшетов любых брендов: ' . $features_ru . ' &#8212; ' . $bue_ru,
            'meta_description_ua' => 'Корпуса та деталі корпуса ' . $wholesaleRetail_ua . ' для смартфонів і планшетів будь-яких брендів: ' . $features_ua . ' &#8212; ' . $bue_ua,
            'meta_keywords_en' => 'Carcase for smartphones and tablets, parts of the case for smartphones and tablets, buy wholesale and retail in Kiev',
            'meta_keywords_ru' => 'Корпуса для смартфонов и планшетов, детали корпуса для смартфонов и планшетов, купить оптом и в розницу в Киеве',
            'meta_keywords_ua' => 'Корпуса для смартфонів і планшетів, деталі корпуса для смартфонів і планшетів, купити оптом і в роздріб в Києві',
            'summary_en' => '<p>The mobile phone case is designed with two purposes: to give the smartphone a presentable appearance and to protect the device\'s parts from mechanical influences.</p><p>Over time, worn out and other traces of exploitation inevitably appear on smartphone and tablet cases. This is especially unpleasant for owners of prestigious phones. Changing the case - in this case, a correct and inexpensive solution.</p><p>However, the problems may not be limited to the appearance. Scales, cracks, loose-fitting rear covers, lost plugs lead to dust and moisture ingress which significantly reduces the life of the phone.</p><p>It is also often necessary to replace buttons, glasses, connectors and other parts of the case.</p><p>In the ' . config('app.name') . ' store you can purchase cases for mobile phones and tablets as well as any spare parts for the phone case: </p><ul><li>Rear covers</li><li>Screen glasses and cameras glasses</li><li >Buttons</li><li>Blankets</li><li>Mounting screws</li><li>Frameworks</li><li>Trays for sim cards</li></ul><p>Case parts - constantly necessary spare parts for service centers. The wholesale price for the hull parts is significantly lower than the retail price.</p>',
            'summary_ru' => '<p>Корпус мобильного телефона проектируется с двумя целями: придать смартфону презентабельный внешний вид и защитить детали устройства от механических воздействий.</p><p>Со временем на корпусах смартфонов и планшетов неизбежно появляются потертости и другие следы эксплуатации. Это особенно неприятно владельцам престижных телефонов. Поменять корпус - в данном случае правильное и недорогое решение.</p><p>Однако проблемы могут не ограничиться внешним видом. Сколы, трещины, неплотно закрывающиеся задние крышки, потерянные заглушки приводят к попаданию внутрь пыли и влаги, &laquo;гниению&raquo; платы, что значительно сокращает срок службы телефона.</p><p>Нередко также требуется замена кнопок, стекол, разъемов и других деталей корпуса.</p><p>В магазине ' . config('app.name') . ' вы можете приобрести корпуса для мобильных телефонов и планшетов в сборе, а также любые запчасти для корпуса телефона:</p><ul><li>Задние крышки</li><li>Стекла экрана и камеры</li><li>Кнопки</li><li>Заглушки</li><li>Крепежные винты</li><li>Каркасы</li><li>Лотки для сим карты</li></ul><p>Корпусные детали - постоянно необходимые запчасти для сервисных центров. Оптовая цена на детали корпуса существенно ниже розничной.</p>',
            'summary_ua' => '<p>Корпус мобільного телефону проектується з двома цілями: надати смартфону презентабельний зовнішній вигляд і захистити деталі пристрою від механічних впливів.</p><p>З часом на корпусах смартфонів і планшетів неминуче з\'являються потертості та інші сліди експлуатації. Це особливо неприємно власникам престижних телефонів. Поміняти корпус - в даному випадку правильне і недороге рішення.</p><p>Однак проблеми можуть не обмежитися зовнішнім виглядом. Відколи, тріщини, задні кришки що нещільно закриваються, втрачені заглушки призводять до потрапляння всередину пилу і вологи, &laquo;гниття&raquo; плати, що значно скорочує термін служби телефону.</p><p>Нерідко також потрібна заміна кнопок, стекол, роз\'ємів та інших деталей корпусу.</p><p>В магазині ' . config('app.name') . 'ви можете придбати корпуса для мобільних телефонів і планшетів в зборі, а також будь-які запчастини для корпусу телефону:</p><ul><li>Задні кришки</li><li>Скло екрану і камери</li><li>Кнопки</li><li>Заглушки</li><li>Гвинти</li><li>Каркаси</li><li>Лотки для сім карти</li></ul><p>Корпусні деталі - постійно необхідні запчастини для сервісних центрів. Оптова ціна на деталі корпуса істотно нижча за роздрібну.</p>',
//
            'children' => [
//                [
//                    'title_ru' => 'Полный корпусной набор',
//                    'title_ua' => 'Повний корпусний набір',
//                    'title_en' => 'Full case set',
//                    'folder' => 'case-set',
//                ],
                [
                    'url' => 'case/rear-cover',
                    'breadcrumb' => 'rear-cover',
                    'image' => 'rear-cover.png',
                    'title_en' => 'Rear covers',
                    'title_ru' => 'Задние крышки',
                    'title_ua' => 'Задні кришки',
                    'page_title_en' => 'Rear-covers for smartphones and tablets',
                    'page_title_ru' => 'Задние крышки к смартфонам и планшетам',
                    'page_title_ua' => 'Задні кришки до смартфонів і планшетів',
                    'meta_title_en' => 'Rear-covers for smartphones and tablets ' . $wholesaleRetail_en,
                    'meta_title_ru' => 'Задние крышки для смартфонов и планшетов ' . $wholesaleRetail_ru,
                    'meta_title_ua' => 'Задні кришки для смартфонів і планшетів ' . $wholesaleRetail_ua,
                    'meta_description_en' => 'Rear-covers ' . $wholesaleRetail_en . ' for smartphones and tablets of any brands:
' . $features_en . ' &#8212; ' . $bue_en,
                    'meta_description_ru' => 'Задние крышки ' . $wholesaleRetail_ru . ' для смартфонов и планшетов любых брендов: ' . $features_ru . ' &#8212; ' . $bue_ru,
                    'meta_description_ua' => 'Задні кришки ' . $wholesaleRetail_ua . ' для смартфонів і планшетів будь-яких брендів: ' . $features_ua . ' &#8212; ' . $bue_ua,
                    'meta_keywords_en' => 'Rear-covers for smartphones, rear-covers for tablets, buy wholesale and retail in Kiev',
                    'meta_keywords_ru' => 'Задние крышки для смартфонов, задние крышки для планшетов, купить оптом и в розницу в Киеве',
                    'meta_keywords_ua' => 'Задні кришки для смартфонів, задні кришки для планшетів, купити оптом і в роздріб в Києві',
                    'summary_en' => '<p>The rear covers of mobile phones close the battery compartment. In addition, they give the phone aesthetic appearance.</p><p>Due to frequent opening, the latches that hold the back cover can break off. Even through a small gap inside the phone can get water and disable it. Over time, the cover is worn out, scratches. In addition, the reason to buy a new cover may be a desire to change its color. </p><p>Shop ' . config('app.name') . ' offers you a large selection of back covers of various colors to any mobile phones. Collectible covers with design patterns will give your phone an individual style.</p>',
                    'summary_ru' => '<p>Задние крышки мобильных телефонов закрывают отсек аккумуляторной батареи. Кроме того они придают телефону эстетический вид.</p><p>Вследствие частого открывания, защелки которые удерживают заднюю крышку могут отломаться. Даже через небольшую щель внутрь телефона может попасть вода и вывести его из строя. Со временем на крышке возникают потертости, царапины. Кроме этого причиной купить новую крышку может стать желание поменять ее цвет.</p><p>Магазин ' . config('app.name') . ' предлагает вам большой выбор задних крышек различных цветов к любым мобильным телефонам. Коллекционные крышки с дизайнерскими рисунками придадут вашому телефону индивидуальный стиль.</p>',
                    'summary_ua' => '<p>Задні кришки мобільних телефонів закривають відсік акумуляторної батареї. Крім того вони надають телефону естетичний вигляд.</p><p>Внаслідок частого відкривання, засувки які утримують задню кришку можуть відламатися. Навіть через невелику щілину всередину телефону може потрапити вода і вивести його з ладу. Згодом на кришці виникають потертості, подряпини. Крім цього причиною купити нову кришку може стати бажання поміняти її колір.</p><p>Магазин ' . config('app.name') . ' пропонує вам великий вибір задніх кришок різних кольорів до будь-яких мобільних телефонів. Колекційні кришки з дизайнерськими малюнками додадуть вашому телефону індивідуальний стиль.</p>',
                ],
                [
                    'url' => 'case/sim-tray',
                    'breadcrumb' => 'sim-tray',
                    'image' => 'sim-tray.jpg',
                    'title_en' => 'SIM card tray',
                    'title_ru' => 'Лоток SIM карты',
                    'title_ua' => 'Лоток SIM карти',
                    'page_title_en' => 'SIM card trays for smartphones and tablets',
                    'page_title_ru' => 'Лотки SIM карты к смартфонам и планшетам',
                    'page_title_ua' => 'Лотки SIM карти до смартфонів і планшетів',
                    'meta_title_en' => 'SIM card trays for smartphones and tablets ' . $wholesaleRetail_en,
                    'meta_title_ru' => 'Лотки SIM карты для смартфонов и планшетов ' . $wholesaleRetail_ru,
                    'meta_title_ua' => 'Лотки SIM карти для смартфонів і планшетів ' . $wholesaleRetail_ua,
                    'meta_description_en' => 'SIM card trays ' . $wholesaleRetail_en . ' for smartphones and tablets of any brands:
' . $features_en . ' &#8212; ' . $bue_en,
                    'meta_description_ru' => 'Лотки SIM карты ' . $wholesaleRetail_ru . ' для смартфонов и планшетов любых брендов: ' . $features_ru . ' &#8212; ' . $bue_ru,
                    'meta_description_ua' => 'Лотки SIM карти ' . $wholesaleRetail_ua . ' для смартфонів і планшетів будь-яких брендів: ' . $features_ua . ' &#8212; ' . $bue_ua,
                    'meta_keywords_en' => 'SIM card trays for smartphones, SIM card trays for tablets, buy wholesale and retail in Kiev',
                    'meta_keywords_ru' => 'Лотки SIM карты для смартфонов, Лотки SIM карты для планшетов, купить оптом и в розницу в Киеве',
                    'meta_keywords_ua' => 'Лотки SIM карти для смартфонів, Лотки SIM карти для планшетів, купити оптом і в роздріб в Києві',
                    'summary_en' => '<p>In many modern smartphones and all Apple phones, the holder (tray) for the SIM card is outside, which allows you to insert a sim without parsing the phone\'s case. Without the tray, you can not lock the SIM in your phone or tablet. This is a small detail that can get lost or broken.</p><p>Store '. config ('app.name') . ' offers you a large selection of SIM card holders of various colors to any mobile phone or tablet.</p>',
                    'summary_ru' => '<p>Во многих современных смартфонах и во всех телефонах Apple держатель (лоток) для SIM карты находится снаружи, что позволяет вставить сим без разбора корпуса телефона. Без лотка невозможно зафиксировать SIM в телефоне или планшете. Это мелкая деталь, которая может потеряться или сломаться.</p><p>Магазин ' . config('app.name') . ' предлагает вам большой выбор держателей (лотков) SIM карт различных цветов к любым мобильным телефонам или планшетам.</p>',
                    'summary_ua' => '<p>У багатьох сучасних смартфонах і у всіх телефонах Apple держатель (лоток) для SIM карти знаходиться зовні, що дозволяє вставити сім без розбору корпусу телефону. Без лотка неможливо зафіксувати SIM в телефоні або планшеті. Це дрібна деталь, яка може загубитися або зламатися.</p><p>Магазин ' . config ('app.name') . ' пропонує вам великий вибір лотків SIM карт різних кольорів до будь-яких мобільних телефонів або планшетів.</p>',
                ],
//                [
//                    'title_ru' => 'Кнопки',
//                    'title_ua' => 'Кнопки',
//                    'title_en' => 'Buttons',
//                    'folder' => 'case-rear-covers',
//                ],
//                [
//                    'title_ru' => 'Средняя часть',
//                    'title_ua' => 'Середня частина',
//                    'title_en' => 'Middle part',
//                    'folder' => 'case-middle-parts',
//                ],
//                [
//                    'title_ru' => 'Стекла',
//                    'title_ua' => 'Стекла',
//                    'title_en' => 'Glasses',
//                    'folder' => 'case-glasses',
//                ],
//                [
//                    'title_ru' => 'Рамки дисплея',
//                    'title_ua' => 'Рамки дисплея',
//                    'title_en' => 'Display frame',
//                    'folder' => 'case-display-frame',
//                ],
//                [
//                    'title_ru' => 'Заглушки',
//                    'title_ua' => 'Заглушки',
//                    'title_en' => 'Plugs',
//                    'folder' => 'case-plugs',
//                ],
//                [
//                    'title_ru' => 'Винты',
//                    'title_ua' => 'Гвинти',
//                    'title_en' => 'Screws',
//                    'folder' => 'case-screws',
//                ],
            ],
        ],
        [
            'url' => 'batteries',
            'breadcrumb' => 'batteries',
            'image' => 'batteries.png',
            'title_en' => 'Batteries',
            'title_ru' => 'Аккумуляторы',
            'title_ua' => 'Акумулятори',
            'page_title_en' => 'Rechargeable batteries for smartphones and tablets',
            'page_title_ru' => 'Аккумуляторные батареи к смартфонам и планшетам',
            'page_title_ua' => 'Акумуляторні батареї до смартфонів і планшетів',
            'meta_title_en' => 'Rechargeable batteries for smartphones and tablets ' . $wholesaleRetail_en,
            'meta_title_ru' => 'Аккумуляторные батареи к смартфонам и планшетам ' . $wholesaleRetail_ru,
            'meta_title_ua' => 'Акумуляторні батареї до смартфонів і планшетів ' . $wholesaleRetail_ua,
            'meta_description_en' => 'Rechargeable batteries ' . $wholesaleRetail_en . ' for smartphones and tablets of any brands:
' . $features_en . ' &#8212; ' . $bue_en,
            'meta_description_ru' => 'Аккумуляторные батареи ' . $wholesaleRetail_ru . ' для смартфонов и планшетов любых брендов: ' . $features_ru . ' &#8212; ' . $bue_ru,
            'meta_description_ua' => 'Акумуляторні батареї ' . $wholesaleRetail_ua . ' для смартфонів і планшетів будь-яких брендів: ' . $features_ua . ' &#8212; ' . $bue_ua,
            'meta_keywords_en' => 'Rechargeable batteries for smartphones and tablets, Batteries for smartphones and tablets, buy wholesale and retail in Kiev',
            'meta_keywords_ru' => 'Аккумуляторные батареи для смартфонов и планшетов, Аккумуляторы для смартфонов и планшетов, купить оптом и в розницу в Киеве',
            'meta_keywords_ua' => 'Акумуляторні батареї для смартфонів і планшетів, Акумулятори для смартфонів і планшетів, купити оптом і в роздріб в Києві',
            'summary_en' => '<p>The battery in the mobile phone and tablet is the spare part that you have to change almost every user. Modern multifunctional mobile devices suggest charging and discharging the battery several times during the day.</p><p>In this mode, any battery will be damaged in time. If your battery is blown, this is a sign of damage to the battery cells and it must definitely be replaced. However, there may be other causes of low battery charge. The charger must match your smartphone or tablet and provide the required charging current. A charge cable with a large internal resistance can lead to a slow charging of the battery. Also, you need to check and clean the battery contacts.</p><p>When buying a battery for a mobile phone, it is preferable to choose the original battery. Store ' . config ('app.name'). ' offers you original batteries for your smartphone or tablet or a copy of the batteries with branded elements inside.</p>',
            'summary_ru' => '<p>Аккумулятор в мобильном телефоне и планшете - это та запчасть, которую приходится менять практически каждому пользователю. Современные многофункциональные мобильные устройства предполагают зарядку и разрядку аккумуляторной батареи по  нескольку раз в течение дня.</p><p>В таком режиме любой аккумулятор со временем повреждается. Если вы заметили вздутие аккумулятора, то это признак повреждения аккумуляторных элементов и его однозначно необходимо заменить. Однако могут быть и другие причины низкой зарядки батареи. Зарядное устройство должно соответствовать вашему смартфону или планшету и выдавать необходимый зарядный ток. Дешевый кабель с большим внутренним сопротивлением может привести к медленной зарядке аккумулятора. Также нужно проверить и почистить контакты аккумуляторной батареи.</p><p>При покупке аккумулятора для мобильного телефона предпочтительно остановить свой выбор на оригинальной батарее. Магазин ' . config('app.name') . ' предлагает вам оригинальные аккумуляторы для вашего смартфона или планшета или копии аккумуляторных батарей с фирменными элементами внутри.</p>',
            'summary_ua' => '<p>Акумулятор в мобільному телефоні і планшеті - це та запчастина, яку доводиться міняти практично кожному користувачеві. Сучасні багатофункціональні мобільні пристрої припускають зарядку і розрядку акумуляторної батареї по кілька разів протягом дня.</p><p>В такому режимі будь-акумулятор з часом пошкоджується. Якщо ви помітили здуття акумулятора, то це ознака пошкодження акумуляторних елементів і його однозначно необхідно замінити. Однак можуть бути й інші причини низької зарядки батареї. Зарядний пристрій повинен відповідати вашому смартфону або планшету і видавати необхідний зарядний струм. Дешевий кабель з великим внутрішнім опором може привести до повільної зарядки акумулятора. Також потрібно перевірити і почистити контакти акумуляторної батареї.</p><p>При покупці акумулятора для мобільного телефону бажано зупинити свій вибір на оригінальній батареї. Магазин ' . config ( 'app.name'). ' пропонує вам оригінальні акумулятори для вашого смартфона або планшета або копії акумуляторних батарей з фірмовими елементами всередині.</p>',
        ],
//        [
//            'title_ru' => 'Шлейфы',
//            'title_ua' => 'Шлейфи',
//            'title_en' => 'Interfaces',
//            'folder' => 'interfaces',
//        ],
//        [
//            'title_ru' => 'Разъемы',
//            'title_ua' => 'Роз\'єми',
//            'title_en' => 'Сonnectors',
//            'folder' => 'connectors',
//        ],
//        [
//            'title_ru' => 'Джойстики и кнопки',
//            'title_ua' => 'Джойстики та кнопки',
//            'title_en' => 'Joysticks and buttons',
//            'folder' => 'buttons',
//        ],
//        [
//            'title_ru' => 'СИМ коннекторы и лотки',
//            'title_ua' => 'СІМ коннектори і лотки',
//            'title_en' => 'SIM connectors and trays',
//            'folder' => 'sim',
//        ],
//        [
//            'title_ru' => 'Динамики',
//            'title_ua' => 'динаміки',
//            'title_en' => 'Speakers',
//            'folder' => 'speakers',
//
//            'children' => [
//                [
//                    'title_ru' => 'Динамики слуховые',
//                    'title_ua' => 'Динаміки слухові',
//                    'title_en' => 'Ear speakers',
//                    'folder' => 'speakers-ear',
//                ],
//                [
//                    'title_ru' => 'Динамики полифонические',
//                    'title_ua' => 'Динаміки поліфонічні',
//                    'title_en' => 'Polyphonic speakers',
//                    'folder' => 'speakers-polyphonic',
//                ],
//            ],
//        ],
//        [
//            'title_ru' => 'Микрофоны',
//            'title_ua' => 'Мікрофони',
//            'title_en' => 'Microphones',
//            'folder' => 'microphones',
//        ],
//        [
//            'title_ru' => 'Камеры',
//            'title_ua' => 'Камери',
//            'title_en' => 'Cameras',
//            'folder' => 'cameras',
//        ],
//        [
//            'title_ru' => 'Микросхемы и платы',
//            'title_ua' => 'Мікросхеми та плати',
//            'title_en' => 'Microchips and boards',
//            'folder' => 'chips',
//
//            'children' => [
//                [
//                    'title_ru' => 'Материнские платы',
//                    'title_ua' => 'Материнські плати',
//                    'title_en' => 'Mother boards',
//                    'folder' => 'boards',
//                ],
//                [
//                    'title_ru' => 'Контроллер питания',
//                    'title_ua' => 'Контролер живлення',
//                    'title_en' => 'Power controller',
//                    'folder' => 'power-controller-chips',
//                ],
//                [
//                    'title_ru' => 'Контроллер Wi-Fi',
//                    'title_ua' => 'Контролер Wi-Fi',
//                    'title_en' => 'Wi-Fi controller',
//                    'folder' => 'wifi-controller-chips',
//                ],
//                [
//                    'title_ru' => 'Контроллер дисплея',
//                    'title_ua' => 'Контролер дисплея',
//                    'title_en' => 'Display controller',
//                    'folder' => 'display-controller-chips',
//                ],
//                [
//                    'title_ru' => 'Контроллер тачскрина',
//                    'title_ua' => 'контролер тачскріна',
//                    'title_en' => 'Touchscreen controller',
//                    'folder' => 'touchscreen-controller-chips',
//                ],
//                [
//                    'title_ru' => 'Аудио контроллер',
//                    'title_ua' => 'Аудіо контролер',
//                    'title_en' => 'Audio controller',
//                    'folder' => 'audio-controller-chips',
//                ],
//                [
//                    'title_ru' => 'Аудио кодек',
//                    'title_ua' => 'Аудіо кодек',
//                    'title_en' => 'Audio codec',
//                    'folder' => 'audio-codec-chips',
//                ],
//                [
//                    'title_ru' => 'USB контроллер',
//                    'title_ua' => 'USB контролер',
//                    'title_en' => 'USB controller',
//                    'folder' => 'usb-controller-chips',
//                ],
//                [
//                    'title_ru' => 'Контроллер подсветки',
//                    'title_ua' => 'Контролер підсвітки',
//                    'title_en' => 'Backlight controller',
//                    'folder' => 'backlight-controller-chips',
//                ],
//                [
//                    'title_ru' => 'Усилитель мощности',
//                    'title_ua' => 'Підсилювач потужності',
//                    'title_en' => 'Amplifier',
//                    'folder' => 'amplifier-chips',
//                ],
//            ],
//        ],
//        [
//            'title_ru' => 'Аксессуары',
//            'title_ua' => 'Аксессуары',
//            'title_en' => 'Accessory',
//            'folder' => 'accessory',
//
//            'children' => [
//                [
//                    'title_ru' => 'Чехлы',
//                    'title_ua' => 'Чохли',
//                    'title_en' => 'Covers',
//                    'folder' => 'covers',
//                ],
//                [
//                    'title_ru' => 'Защитные пленки и стекла',
//                    'title_ua' => 'Захисні плівки та стекла',
//                    'title_en' => 'Protective sticker and glass',
//                    'folder' => 'sticker',
//                ],
//                [
//                    'title_ru' => 'Кабели, переходники, зарядки',
//                    'title_ua' => 'Кабелі, перехідники, зарядки',
//                    'title_en' => 'Cables, adapters, chargers',
//                    'folder' => 'cables',
//                ],
//                [
//                    'title_ru' => 'наушники',
//                    'title_ua' => 'наушники',
//                    'title_en' => 'headphones',
//                    'folder' => 'headphones',
//                ],
//            ],
//        ],
//        [
//            'title_ru' => 'Гаджеты',
//            'title_ua' => 'Гаджети',
//            'title_en' => 'Gadgets',
//            'folder' => 'gadgets',
//
//            'children' => [
//                [
//                    'title_ru' => 'Фитнес-браслеты',
//                    'title_ua' => 'Фітнес-браслети',
//                    'title_en' => 'Fitness bracelets',
//                    'folder' => 'fitness',
//                ],
//            ],
//        ],
    ],
];