<?php

/**
 * Array of models by brands and series.
 */
$bue_en = trans('meta.phrases.bue', [], 'en');
$features_en = trans('meta.phrases.features', [], 'en');
$wholesaleRetail_en = trans('meta.phrases.wholesale_and_retail', [], 'en');
$originalCopy_en = trans('meta.phrases.original_and_copy', [], 'en');

$bue_ru = trans('meta.phrases.bue', [], 'ru');
$features_ru = trans('meta.phrases.features', [], 'ru');
$wholesaleRetail_ru = trans('meta.phrases.wholesale_and_retail', [], 'ru');
$originalCopy_ru = trans('meta.phrases.original_and_copy', [], 'ru');

$bue_ua = trans('meta.phrases.bue', [], 'ua');
$features_ua = trans('meta.phrases.features', [], 'ua');
$wholesaleRetail_ua = trans('meta.phrases.wholesale_and_retail', [], 'ua');
$originalCopy_ua = trans('meta.phrases.original_and_copy', [], 'ua');

return [
    'Apple' => [
        'iPad' => [
//            [
//                'title' => 'iPad 1',
//                'breadcrumb' => 'ipad-1',
//                'url' => 'apple/ipad-1',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad 1',
//                'meta_keywords_ru' => 'Apple iPad 1',
//                'meta_keywords_ua' => 'Apple iPad 1',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPad 2',
//                'breadcrumb' => 'ipad-2',
//                'url' => 'apple/ipad-2',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad 2',
//                'meta_keywords_ru' => 'Apple iPad 2',
//                'meta_keywords_ua' => 'Apple iPad 2',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPad 3',
//                'breadcrumb' => 'ipad-3',
//                'url' => 'apple/ipad-3',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad 3',
//                'meta_keywords_ru' => 'Apple iPad 3',
//                'meta_keywords_ua' => 'Apple iPad 3',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPad 4',
//                'breadcrumb' => 'ipad-4',
//                'url' => 'apple/ipad-4',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad 4',
//                'meta_keywords_ru' => 'Apple iPad 4',
//                'meta_keywords_ua' => 'Apple iPad 4',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPad Air',
//                'breadcrumb' => 'ipad-air',
//                'url' => 'apple/ipad-air',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad Air',
//                'meta_keywords_ru' => 'Apple iPad Air',
//                'meta_keywords_ua' => 'Apple iPad Air',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPad Air2',
//                'breadcrumb' => 'ipad-air2',
//                'url' => 'apple/ipad-air2',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad Air2',
//                'meta_keywords_ru' => 'Apple iPad Air2',
//                'meta_keywords_ua' => 'Apple iPad Air2',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPad Mini',
//                'breadcrumb' => 'ipad-mini',
//                'url' => 'apple/ipad-mini',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad Mini',
//                'meta_keywords_ru' => 'Apple iPad Mini',
//                'meta_keywords_ua' => 'Apple iPad Mini',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPad Mini2',
//                'breadcrumb' => 'ipad-mini2',
//                'url' => 'apple/ipad-mini2',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad Mini2',
//                'meta_keywords_ru' => 'Apple iPad Mini2',
//                'meta_keywords_ua' => 'Apple iPad Mini2',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPad Mini3',
//                'breadcrumb' => 'ipad-mini3',
//                'url' => 'apple/ipad-mini3',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad Mini3',
//                'meta_keywords_ru' => 'Apple iPad Mini3',
//                'meta_keywords_ua' => 'Apple iPad Mini3',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPad Mini4',
//                'breadcrumb' => 'ipad-mini4',
//                'url' => 'apple/ipad-mini4',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad Mini4',
//                'meta_keywords_ru' => 'Apple iPad Mini4',
//                'meta_keywords_ua' => 'Apple iPad Mini4',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPad pro',
//                'breadcrumb' => 'ipad-pro',
//                'url' => 'apple/ipad-pro',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPad pro',
//                'meta_keywords_ru' => 'Apple iPad pro',
//                'meta_keywords_ua' => 'Apple iPad pro',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
        ],
//        'iPod' => [
//            [
//                'title' => 'iPod touch 4',
//                'breadcrumb' => 'ipod-touch-4',
//                'url' => 'apple/ipod-touch-4',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPod touch 4',
//                'meta_keywords_ru' => 'Apple iPod touch 4',
//                'meta_keywords_ua' => 'Apple iPod touch 4',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPod touch 5',
//                'breadcrumb' => 'ipod-touch-5',
//                'url' => 'apple/ipod-touch-5',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPod touch 5',
//                'meta_keywords_ru' => 'Apple iPod touch 5',
//                'meta_keywords_ua' => 'Apple iPod touch 5',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPod touch 6',
//                'breadcrumb' => 'ipod-touch-6',
//                'url' => 'apple/ipod-touch-6',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPod touch 6',
//                'meta_keywords_ru' => 'Apple iPod touch 6',
//                'meta_keywords_ua' => 'Apple iPod touch 6',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPod Nano 6',
//                'breadcrumb' => 'ipod-nano-6',
//                'url' => 'apple/ipod-nano-6',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPod Nano 6',
//                'meta_keywords_ru' => 'Apple iPod Nano 6',
//                'meta_keywords_ua' => 'Apple iPod Nano 6',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPod Nano 7',
//                'breadcrumb' => 'ipod-nano-7',
//                'url' => 'apple/ipod-nano-7',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPod Nano 7',
//                'meta_keywords_ru' => 'Apple iPod Nano 7',
//                'meta_keywords_ua' => 'Apple iPod Nano 7',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//        ],
        'iPhone' => [
//            [
//                'title' => 'iPhone 3g',
//                'breadcrumb' => 'iphone-3g',
//                'url' => 'apple/iphone-3g',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 3g',
//                'meta_keywords_ru' => 'Apple iPhone 3g',
//                'meta_keywords_ua' => 'Apple iPhone 3g',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPhone 3s',
//                'breadcrumb' => 'iphone-3s',
//                'url' => 'apple/iphone-3s',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 3s',
//                'meta_keywords_ru' => 'Apple iPhone 3s',
//                'meta_keywords_ua' => 'Apple iPhone 3s',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPhone 4',
//                'breadcrumb' => 'iphone-4',
//                'url' => 'apple/iphone-4',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 4',
//                'meta_keywords_ru' => 'Apple iPhone 4',
//                'meta_keywords_ua' => 'Apple iPhone 4',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPhone 4s',
//                'breadcrumb' => 'iphone-4s',
//                'url' => 'apple/iphone-4s',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 4s',
//                'meta_keywords_ru' => 'Apple iPhone 4s',
//                'meta_keywords_ua' => 'Apple iPhone 4s',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPhone 5',
//                'breadcrumb' => 'iphone-5',
//                'url' => 'apple/iphone-5',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 5',
//                'meta_keywords_ru' => 'Apple iPhone 5',
//                'meta_keywords_ua' => 'Apple iPhone 5',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPhone 5c',
//                'breadcrumb' => 'iphone-5c',
//                'url' => 'apple/iphone-5c',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 5c',
//                'meta_keywords_ru' => 'Apple iPhone 5c',
//                'meta_keywords_ua' => 'Apple iPhone 5c',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
            [
                'url' => 'apple/iphone-5s',
                'breadcrumb' => 'iphone-5s',
                'image' => null,
                'title' => 'iPhone 5s',
                'page_title_en' => 'Spare parts for smartphones Apple iPhone 5s',
                'page_title_ru' => 'Запчасти к смартфонам Apple iPhone 5s',
                'page_title_ua' => 'Запчастини до смартфонів Apple iPhone 5s',
                'meta_title_en' => 'Spare parts for smartphones Apple iPhone 5s ' . $wholesaleRetail_en,
                'meta_title_ru' => 'Запчасти к смартфонам Apple iPhone 5s ' . $wholesaleRetail_ru,
                'meta_title_ua' => 'Запчастини до смартфонів Apple iPhone 5s ' . $wholesaleRetail_ua,
                'meta_description_en' => 'Spare parts for smartphones Apple iPhone 5s. ' . ucfirst($wholesaleRetail_en). ', ' . $originalCopy_en . '. ' . ucfirst($features_en) . ' &#8212; ' . $bue_en,
                'meta_description_ru' => 'Запчасти к смартфонам Apple iPhone 5s. ' . ucfirst($wholesaleRetail_ru). ', ' . $originalCopy_ru . '. ' . ucfirst($features_ru) . ' &#8212; ' . $bue_ru,
                'meta_description_ua' => 'Запчастини до смартфонів Apple iPhone 5s. ' . ucfirst($wholesaleRetail_ua). ', ' . $originalCopy_ua . '. ' . ucfirst($features_ua) . ' &#8212; ' . $bue_ua,
                'meta_keywords_en' => 'Apple iPhone 5s',
                'meta_keywords_ru' => 'Apple iPhone 5s',
                'meta_keywords_ua' => 'Apple iPhone 5s',
                'summary_en' => '<p>iPhone&nbsp;5s is an out-of-date, but still popular, model of Apple\'s smartphone due to its low cost. This model has long been discontinued, so the age of iPhone 5s - from several years and older, which because of its reliability continue to work.</p><p>However, over time some parts of mobile phones will be damaged that have to buy and replace them.</p><p>Our ' . config ('app.name'). ' shop offers you a wide selection of spare parts for smartphones Apple iPhone&nbsp;5s: touchscreens, separate and assembled with a screen cameras, cases, cables, microphones, speakers and any other details. You can buy copies of the highest quality parts, the restored original spare parts or the serviceable components removed from the disassembled devices.</p>',
                'summary_ru' => '<p>iPhone&nbsp;5s - устаревшая, но все еще популярная благодаря своей дешевизне модель смартфона Apple. Данная модель давно снята с производства, поэтому возраст телефонов iPhone&nbsp;5s - от нескольких лет и старше, которые благодаря своей надежности продолжают работать.</p><p>Однако время берет свое и в мобильных телефонах выходят из строя запчасти, которые приходится покупать и заменять.</p><p>Магазин ' . config ('app.name'). ' предлагает вам широкий выбор запчастей к смартфонам Apple iPhone&nbsp;5s : сенсорные дисплеи, камеры отдельно и в сборе с экраном, корпуса, шлейфы, микрофоны, динамики и любые другие детали. Вы можете купить копии запчастей высшего качества,восстановленные оригинальные запчасти или снятые с разобранных аппаратов исправные комплектующие.</p>',
                'summary_ua' => '<p>iPhone&nbsp;5s - застаріла, але все ще популярна завдяки своїй дешевизні модель смартфона Apple. Дана модель давно знята з виробництва, тому вік телефонів iPhone&nbsp;5s - від декількох років і старше, які завдяки своїй надійності продовжують працювати.</p><p> Однак час бере своє і в мобільних телефонах виходять з ладу запчастини, які доводиться купувати і замінювати.</p><p> Магазин '. config ( 'app.name'). ' пропонує вам широкий вибір запчастин до смартфонів Apple iPhone&nbsp;5s : сенсорні дисплеї, камери окремо і в зборі з екраном, корпуси, шлейфи, мікрофони, динаміки і будь-які інші деталі. Ви можете купити копії запчастин вищої якості, відновлені оригінальні запчастини або зняті з розібраних апаратів справні комплектуючі.</p>',
            ],
            [
                'url' => 'apple/iphone-6',
                'breadcrumb' => 'iphone-6',
                'image' => null,
                'title' => 'iPhone 6',
                'page_title_en' => 'Spare parts for smartphones Apple iPhone 6',
                'page_title_ru' => 'Запчасти к смартфонам Apple iPhone 6',
                'page_title_ua' => 'Запчастини до смартфонів Apple iPhone 6',
                'meta_title_en' => 'Spare parts for smartphones Apple iPhone 6 ' . $wholesaleRetail_en,
                'meta_title_ru' => 'Запчасти к смартфонам Apple iPhone 6 ' . $wholesaleRetail_ru,
                'meta_title_ua' => 'Запчастини до смартфонів Apple iPhone 6 ' . $wholesaleRetail_ua,
                'meta_description_en' => 'Spare parts for smartphones Apple iPhone 6. ' . ucfirst($wholesaleRetail_en). ', ' . $originalCopy_en . '. ' . ucfirst($features_en) . ' &#8212; ' . $bue_en,
                'meta_description_ru' => 'Запчасти к смартфонам Apple iPhone 6. ' . ucfirst($wholesaleRetail_ru). ', ' . $originalCopy_ru . '. ' . ucfirst($features_ru) . ' &#8212; ' . $bue_ru,
                'meta_description_ua' => 'Запчастини до смартфонів Apple iPhone 6. ' . ucfirst($wholesaleRetail_ua). ', ' . $originalCopy_ua . '. ' . ucfirst($features_ua) . ' &#8212; ' . $bue_ua,
                'meta_keywords_en' => 'Spare parts Apple iPhone 6',
                'meta_keywords_ru' => 'Запчасти Apple iPhone 6',
                'meta_keywords_ua' => 'Запчастини Apple iPhone 6',
                'summary_en' => '<p>iPhone&nbsp;6 is new series of smartphones from Apple.</p><p>Smartphone Apple iPhone&nbsp;6 have been made several changes. The screen size increased to 4.7&Prime; with a resolution of 1334 × 750 px. A camera with an improved sensor and lens was used. The design of the case has changed.</p><p>However, these changes have caused some problems. Some parts of the smartphone became more often damaged. The increased screen size is more prone to damage. Usually the sensor suffers. Unfortunately if you have a broken touchscreen, you will have to buy the whole screen with the sensor. There were reports of problems with the phone\'s body, which bent from excessive squeezing. In this case, you need to purchase a new housing. Over time, in the iPhone&nbsp;6 may be damaged a camera, speaker, microphone or other parts. </p><p>In the ' . config ('app.name'). ' store you can buy original spare parts for the mobile phone Apple iPhone&nbsp;6 or high-quality copies (AAA quality).</p>',
                'summary_ru' => '<p>iPhone&nbsp;6 - новая серия смартфонов от компании Apple.</p><p>По сравнению с предыдущими моделями в телефон Apple iPhone&nbsp;6 были внесены существенные изменения.Увеличился размер экрана до 4.7&Prime; с разрешением 1334 × 750 px. Использована камера с улучшенным сенсором и объективом. Изменился дизайн корпуса.</p><p>Однако эти изменения породили дополнительные проблемы. Некоторые запчасти смартфона стали чаще выходить из строя. Увеличенный размер экрана больше подвержен повреждениям. Обычно страдает сенсор. К сожалению Если у вас вышел из строя тачскрин, придется купить весь экран в с боре с сенсором. Были сообщения о проблемах с корпусом телефона, который гнулся от чрезмерного сдавливания. В данном случае необходимо приобрести новый корпус. Со временем в смартфоне iPhone&nbsp;6 могут выйти из строя камера, динамик, микрофон или другие запчасти.</p><p>В магазине ' . config ('app.name'). ' вы можете купить оригинальные запчасти к мобильному телефону Apple iPhone&nbsp;6 либо высококачественные копии (AAA качество).</p>',
                'summary_ua' => '<p>iPhone&nbsp;6 - нова серія смартфонів від компанії Apple. </p><p>У порівнянні з попередніми моделями в телефон Apple iPhone&nbsp;6 були внесені істотні зміни. Збільшився розмір екрану до 4.7&Prime; з роздільною здатністю 1334 × 750 px. Використана камера з поліпшеним сенсором і об\'єктивом. Змінився дизайн корпусу.</p><p>Однак ці зміни породили додаткові проблеми. Деякі запчастини смартфона стали частіше пошкоджуватися. Збільшений розмір екрану більше схильний до пошкоджень. Зазвичай страждає сенсор. На жаль якщо у вас вийшов з ладу тачскрін, доведеться купити весь екран в зборі з сенсором. Були повідомлення про проблеми з корпусом телефону, який гнувся від надмірного стискання. В даному випадку необхідно придбати новий корпус. Згодом в смартфоні iPhone&nbsp;6 можуть вийти з ладу камера, динамік, мікрофон або інші запчастини.</p><p>В магазині ' . config ( 'app.name') . ' ви можете купити оригінальні запчастини до мобільного телефону Apple iPhone&nbsp;6 або високоякісні копії (AAA якість).</p>',
            ],
//            [
//                'title' => 'iPhone 6 Plus',
//                'breadcrumb' => 'iphone-6-plus',
//                'url' => 'apple/iphone-6-plus',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 6 Plus',
//                'meta_keywords_ru' => 'Apple iPhone 6 Plus',
//                'meta_keywords_ua' => 'Apple iPhone 6 Plus',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPhone 6s',
//                'breadcrumb' => 'iphone-6s',
//                'url' => 'apple/iphone-6s',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 6s',
//                'meta_keywords_ru' => 'Apple iPhone 6s',
//                'meta_keywords_ua' => 'Apple iPhone 6s',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPhone 6s Plus',
//                'breadcrumb' => 'iphone-6s-plus',
//                'url' => 'apple/iphone-6s-plus',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 6s Plus',
//                'meta_keywords_ru' => 'Apple iPhone 6s Plus',
//                'meta_keywords_ua' => 'Apple iPhone 6s Plus',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPhone 7',
//                'breadcrumb' => 'iphone-7',
//                'url' => 'apple/iphone-7',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 7',
//                'meta_keywords_ru' => 'Apple iPhone 7',
//                'meta_keywords_ua' => 'Apple iPhone 7',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'iPhone 7 Plus',
//                'breadcrumb' => 'iphone-7-plus',
//                'url' => 'apple/iphone-7-plus',
//                'image' => null,
//                'meta_keywords_en' => 'Apple iPhone 7 Plus',
//                'meta_keywords_ru' => 'Apple iPhone 7 Plus',
//                'meta_keywords_ua' => 'Apple iPhone 7 Plus',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
        ],
    ],
//    'Motorola' => [
//        'Moto X' => [
//            [
//                'title' => 'Moto X XT1053',
//                'breadcrumb' => 'moto-x-xt1053',
//                'url' => 'motorola/moto-x-xt1053',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto X XT1053',
//                'meta_keywords_ru' => 'Motorola Moto X XT1053',
//                'meta_keywords_ua' => 'Motorola Moto X XT1053',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto X XT1561',
//                'breadcrumb' => 'moto-x-xt1561',
//                'url' => 'motorola/moto-x-xt1561',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto X XT1561',
//                'meta_keywords_ru' => 'Motorola Moto X XT1561',
//                'meta_keywords_ua' => 'Motorola Moto X XT1561',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto X XT1562',
//                'breadcrumb' => 'moto-x-xt1562',
//                'url' => 'motorola/moto-x-xt1562',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto X XT1562',
//                'meta_keywords_ru' => 'Motorola Moto X XT1562',
//                'meta_keywords_ua' => 'Motorola Moto X XT1562',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto X XT1563',
//                'breadcrumb' => 'moto-x-xt1563',
//                'url' => 'motorola/moto-x-xt1563',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto X XT1563',
//                'meta_keywords_ru' => 'Motorola Moto X XT1563',
//                'meta_keywords_ua' => 'Motorola Moto X XT1563',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto X XT1570',
//                'breadcrumb' => 'moto-x-xt1570',
//                'url' => 'motorola/moto-x-xt1570',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto X XT1570',
//                'meta_keywords_ru' => 'Motorola Moto X XT1570',
//                'meta_keywords_ua' => 'Motorola Moto X XT1570',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto X XT1572',
//                'breadcrumb' => 'moto-x-xt1572',
//                'url' => 'motorola/moto-x-xt1572',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto X XT1572',
//                'meta_keywords_ru' => 'Motorola Moto X XT1572',
//                'meta_keywords_ua' => 'Motorola Moto X XT1572',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto X XT1575',
//                'breadcrumb' => 'moto-x-xt1575',
//                'url' => 'motorola/moto-x-xt1575',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto X XT1575',
//                'meta_keywords_ru' => 'Motorola Moto X XT1575',
//                'meta_keywords_ua' => 'Motorola Moto X XT1575',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//        ],
//        'Moto G' => [
//            [
//                'title' => 'Moto G XT1032',
//                'breadcrumb' => 'moto-g-xt1032',
//                'url' => 'motorola/moto-g-xt1032',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto G XT1032',
//                'meta_keywords_ru' => 'Motorola Moto G XT1032',
//                'meta_keywords_ua' => 'Motorola Moto G XT1032',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto G XT1033',
//                'breadcrumb' => 'moto-g-xt1033',
//                'url' => 'motorola/moto-g-xt1033',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto G XT1033',
//                'meta_keywords_ru' => 'Motorola Moto G XT1033',
//                'meta_keywords_ua' => 'Motorola Moto G XT1033',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto G XT1036',
//                'breadcrumb' => 'moto-g-xt1036',
//                'url' => 'motorola/moto-g-xt1036',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto G XT1036',
//                'meta_keywords_ru' => 'Motorola Moto G XT1036',
//                'meta_keywords_ua' => 'Motorola Moto G XT1036',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto G XT1063',
//                'breadcrumb' => 'moto-g-xt1063',
//                'url' => 'motorola/moto-g-xt1063',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto G XT1063',
//                'meta_keywords_ru' => 'Motorola Moto G XT1063',
//                'meta_keywords_ua' => 'Motorola Moto G XT1063',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto G XT1068',
//                'breadcrumb' => 'moto-g-xt1068',
//                'url' => 'motorola/moto-g-xt1068',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto G XT1068',
//                'meta_keywords_ru' => 'Motorola Moto G XT1068',
//                'meta_keywords_ua' => 'Motorola Moto G XT1068',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto G XT1540',
//                'breadcrumb' => 'moto-g-xt1540',
//                'url' => 'motorola/moto-g-xt1540',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto G XT1540',
//                'meta_keywords_ru' => 'Motorola Moto G XT1540',
//                'meta_keywords_ua' => 'Motorola Moto G XT1540',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Moto G XT1541',
//                'breadcrumb' => 'moto-g-xt1541',
//                'url' => 'motorola/moto-g-xt1541',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Moto G XT1541',
//                'meta_keywords_ru' => 'Motorola Moto G XT1541',
//                'meta_keywords_ua' => 'Motorola Moto G XT1541',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//        ],
//        'Nexus 6' => [
//            [
//                'title' => 'Nexus 6 XT1100',
//                'breadcrumb' => 'nexus-6-xt1100',
//                'url' => 'motorola/nexus-6-xt1100',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Nexus 6 XT1100',
//                'meta_keywords_ru' => 'Motorola Nexus 6 XT1100',
//                'meta_keywords_ua' => 'Motorola Nexus 6 XT1100',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Nexus 6 XT1103',
//                'breadcrumb' => 'nexus-6-xt1103',
//                'url' => 'motorola/nexus-6-xt1103',
//                'image' => null,
//                'meta_keywords_en' => 'Motorola Nexus 6 XT1103',
//                'meta_keywords_ru' => 'Motorola Nexus 6 XT1103',
//                'meta_keywords_ua' => 'Motorola Nexus 6 XT1103',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//        ],
//    ],
//    'OnePlus' => [
//        '' => [
//            [
//                'title' => 'OnePlus One',
//                'breadcrumb' => 'oneplus-one',
//                'url' => 'oneplus/oneplus-one',
//                'image' => null,
//                'meta_keywords_en' => 'OnePlus One',
//                'meta_keywords_ru' => 'OnePlus One',
//                'meta_keywords_ua' => 'OnePlus One',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'OnePlus 2',
//                'breadcrumb' => 'oneplus-2',
//                'url' => 'oneplus/oneplus-2',
//                'image' => null,
//                'meta_keywords_en' => 'OnePlus 2',
//                'meta_keywords_ru' => 'OnePlus 2',
//                'meta_keywords_ua' => 'OnePlus 2',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'OnePlus 3',
//                'breadcrumb' => 'oneplus-3',
//                'url' => 'oneplus/oneplus-3',
//                'image' => null,
//                'meta_keywords_en' => 'OnePlus 3',
//                'meta_keywords_ru' => 'OnePlus 3',
//                'meta_keywords_ua' => 'OnePlus 3',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//        ],
//    ],
//    'Fly' => [
//        '' => [
//            [
//                'title' => 'IQ4415 ERA STYLE 3',
//                'breadcrumb' => 'iq4415-era-style-3',
//                'url' => 'fly/iq4415-era-style-3',
//                'image' => null,
//                'meta_keywords_en' => 'Fly IQ4415 ERA STYLE 3',
//                'meta_keywords_ru' => 'Fly IQ4415 ERA STYLE 3',
//                'meta_keywords_ua' => 'Fly IQ4415 ERA STYLE 3',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'IQ4416 ERA LIFE 5',
//                'breadcrumb' => 'iq4416-era-life-5',
//                'url' => 'fly/iq4416-era-life-5',
//                'image' => null,
//                'meta_keywords_en' => 'Fly IQ4416 ERA LIFE 5',
//                'meta_keywords_ru' => 'Fly IQ4416 ERA LIFE 5',
//                'meta_keywords_ua' => 'Fly IQ4416 ERA LIFE 5',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'FS401 STRATUS 1',
//                'breadcrumb' => 'fs401-stratus-1',
//                'url' => 'fly/fs401-stratus-1',
//                'image' => null,
//                'meta_keywords_en' => 'Fly FS401 STRATUS 1',
//                'meta_keywords_ru' => 'Fly FS401 STRATUS 1',
//                'meta_keywords_ua' => 'Fly FS401 STRATUS 1',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'FS403 CUMULUS 1',
//                'breadcrumb' => 'fs403-cumulus-1',
//                'url' => 'fly/fs403-cumulus-1',
//                'image' => null,
//                'meta_keywords_en' => 'Fly FS403 CUMULUS 1',
//                'meta_keywords_ru' => 'Fly FS403 CUMULUS 1',
//                'meta_keywords_ua' => 'Fly FS403 CUMULUS 1',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'IQ4410 QUAD PHOENIX',
//                'breadcrumb' => 'iq4410-quad-phoenix',
//                'url' => 'fly/iq4410-quad-phoenix',
//                'image' => null,
//                'meta_keywords_en' => 'Fly IQ4410 QUAD PHOENIX',
//                'meta_keywords_ru' => 'Fly IQ4410 QUAD PHOENIX',
//                'meta_keywords_ua' => 'Fly IQ4410 QUAD PHOENIX',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'FS451 NIMBUS 1',
//                'breadcrumb' => 'fs451-nimbus-1',
//                'url' => 'fly/fs451-nimbus-1',
//                'image' => null,
//                'meta_keywords_en' => 'Fly FS451 NIMBUS 1',
//                'meta_keywords_ru' => 'Fly FS451 NIMBUS 1',
//                'meta_keywords_ua' => 'Fly FS451 NIMBUS 1',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'FS451 NIMBUS 2',
//                'breadcrumb' => 'fs451-nimbus-2',
//                'url' => 'fly/fs451-nimbus-2',
//                'image' => null,
//                'meta_keywords_en' => 'Fly FS451 NIMBUS 2',
//                'meta_keywords_ru' => 'Fly FS451 NIMBUS 2',
//                'meta_keywords_ua' => 'Fly FS451 NIMBUS 2',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'IQ446 MAGIC',
//                'breadcrumb' => 'iq446-magic',
//                'url' => 'fly/iq446-magic',
//                'image' => null,
//                'meta_keywords_en' => 'Fly IQ446 MAGIC',
//                'meta_keywords_ru' => 'Fly IQ446 MAGIC',
//                'meta_keywords_ua' => 'Fly IQ446 MAGIC',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//        ],
//    ],
//    'BlackBerry' => [
//        '' => [
//            [
//                'title' => 'BlackBerry 9100',
//                'breadcrumb' => 'blackberry-9100',
//                'url' => 'blackberry/blackberry-9100',
//                'image' => null,
//                'meta_keywords_en' => 'BlackBerry 9100',
//                'meta_keywords_ru' => 'BlackBerry 9100',
//                'meta_keywords_ua' => 'BlackBerry 9100',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'BlackBerry Z10',
//                'breadcrumb' => 'blackberry-z10',
//                'url' => 'blackberry/blackberry-z10',
//                'image' => null,
//                'meta_keywords_en' => 'BlackBerry Z10',
//                'meta_keywords_ru' => 'BlackBerry Z10',
//                'meta_keywords_ua' => 'BlackBerry Z10',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'BlackBerry Z30',
//                'breadcrumb' => 'blackberry-z30',
//                'url' => 'blackberry/blackberry-z30',
//                'image' => null,
//                'meta_keywords_en' => 'BlackBerry Z30',
//                'meta_keywords_ru' => 'BlackBerry Z30',
//                'meta_keywords_ua' => 'BlackBerry Z30',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//        ],
//    ],
//    'Meizu' => [
//        '' => [
//            [
//                'title' => 'Meizu M3 Note',
//                'breadcrumb' => 'meizu-m3-note',
//                'url' => 'meizu/meizu-m3-note',
//                'image' => null,
//                'meta_keywords_en' => 'Meizu M3 Note',
//                'meta_keywords_ru' => 'Meizu M3 Note',
//                'meta_keywords_ua' => 'Meizu M3 Note',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Meizu Pro 6',
//                'breadcrumb' => 'meizu-pro-6',
//                'url' => 'meizu/meizu-pro-6',
//                'image' => null,
//                'meta_keywords_en' => 'Meizu Pro 6',
//                'meta_keywords_ru' => 'Meizu Pro 6',
//                'meta_keywords_ua' => 'Meizu Pro 6',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Meizu MX2',
//                'breadcrumb' => 'meizu-mx2',
//                'url' => 'meizu/meizu-mx2',
//                'image' => null,
//                'meta_keywords_en' => 'Meizu MX2',
//                'meta_keywords_ru' => 'Meizu MX2',
//                'meta_keywords_ua' => 'Meizu MX2',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Meizu MX3',
//                'breadcrumb' => 'meizu-mx3',
//                'url' => 'meizu/meizu-mx3',
//                'image' => null,
//                'meta_keywords_en' => 'Meizu MX3',
//                'meta_keywords_ru' => 'Meizu MX3',
//                'meta_keywords_ua' => 'Meizu MX3',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Meizu MX4',
//                'breadcrumb' => 'meizu-mx4',
//                'url' => 'meizu/meizu-mx4',
//                'image' => null,
//                'meta_keywords_en' => 'Meizu MX4',
//                'meta_keywords_ru' => 'Meizu MX4',
//                'meta_keywords_ua' => 'Meizu MX4',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Meizu MX5',
//                'breadcrumb' => 'meizu-mx5',
//                'url' => 'meizu/meizu-mx5',
//                'image' => null,
//                'meta_keywords_en' => 'Meizu MX5',
//                'meta_keywords_ru' => 'Meizu MX5',
//                'meta_keywords_ua' => 'Meizu MX5',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Meizu M1',
//                'breadcrumb' => 'meizu-m1',
//                'url' => 'meizu/meizu-m1',
//                'image' => null,
//                'meta_keywords_en' => 'Meizu M1',
//                'meta_keywords_ru' => 'Meizu M1',
//                'meta_keywords_ua' => 'Meizu M1',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'Meizu M2',
//                'breadcrumb' => 'meizu-m2',
//                'url' => 'meizu/meizu-m2',
//                'image' => null,
//                'meta_keywords_en' => 'Meizu M2',
//                'meta_keywords_ru' => 'Meizu M2',
//                'meta_keywords_ua' => 'Meizu M2',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//        ],
//    ],
//    'OPPO' => [
//        '' => [
//            [
//                'title' => 'OPPO Find 5',
//                'breadcrumb' => 'oppo-find-5',
//                'url' => 'oppo/oppo-find-5',
//                'image' => null,
//                'meta_keywords_en' => 'OPPO Find 5',
//                'meta_keywords_ru' => 'OPPO Find 5',
//                'meta_keywords_ua' => 'OPPO Find 5',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'OPPO Find 5 Mini',
//                'breadcrumb' => 'oppo-find-5-mini',
//                'url' => 'oppo/oppo-find-5-mini',
//                'image' => null,
//                'meta_keywords_en' => 'OPPO Find 5 Mini',
//                'meta_keywords_ru' => 'OPPO Find 5 Mini',
//                'meta_keywords_ua' => 'OPPO Find 5 Mini',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//            [
//                'title' => 'OPPO Find 7',
//                'breadcrumb' => 'oppo-find-7',
//                'url' => 'oppo/oppo-find-7',
//                'image' => null,
//                'meta_keywords_en' => 'OPPO Find 7',
//                'meta_keywords_ru' => 'OPPO Find 7',
//                'meta_keywords_ua' => 'OPPO Find 7',
//                'page_title_en' => '',
//                'page_title_ru' => '',
//                'page_title_ua' => '',
//                'meta_title_en' => '',
//                'meta_title_ru' => '',
//                'meta_title_ua' => '',
//                'meta_description_en' => '',
//                'meta_description_ru' => '',
//                'meta_description_ua' => '',
//                'summary_en' => '',
//                'summary_ru' => '',
//                'summary_ua' => '',
//            ],
//        ],
//    ],
    'Lenovo' => [
        'A series' => [
            [
                'url' => 'Lenovo/a316',
                'breadcrumb' => 'a316',
                'image' => null,
                'title' => 'A316',
                'page_title_en' => 'Spare parts for smartphones Lenovo A316',
                'page_title_ru' => 'Запчасти к смартфонам Lenovo A316',
                'page_title_ua' => 'Запчастини до смартфонів Lenovo A316',
                'meta_title_en' => 'Spare parts for smartphones Lenovo A316 ' . $wholesaleRetail_en,
                'meta_title_ru' => 'Запчасти к смартфонам Lenovo A316 ' . $wholesaleRetail_ru,
                'meta_title_ua' => 'Запчастини до смартфонів Lenovo A316 ' . $wholesaleRetail_ua,
                'meta_description_en' => 'Spare parts for smartphones Lenovo A316. ' . ucfirst($wholesaleRetail_en). ', ' . $originalCopy_en . '. ' . ucfirst($features_en) . ' &#8212; ' . $bue_en,
                'meta_description_ru' => 'Запчасти к смартфонам Lenovo A316. ' . ucfirst($wholesaleRetail_ru). ', ' . $originalCopy_ru . '. ' . ucfirst($features_ru) . ' &#8212; ' . $bue_ru,
                'meta_description_ua' => 'Запчастини до смартфонів Lenovo A316. ' . ucfirst($wholesaleRetail_ua). ', ' . $originalCopy_ua . '. ' . ucfirst($features_ua) . ' &#8212; ' . $bue_ua,
                'meta_keywords_en' => 'Lenovo A316',
                'meta_keywords_ru' => 'Lenovo A316',
                'meta_keywords_ua' => 'Lenovo A316',
                'summary_en' => '<p>' . config ('app.name'). ' shop offers original spare parts and high quality copies for the Lenovo A316 smartphone wholesale and retail.</p>',
                'summary_ru' => '<p>Магазин '. config ( 'app.name'). ' предлагает оригинальные запчасти и копии высокого качества к смартфону Lenovo A316 оптом и в розницу.</p>',
                'summary_ua' => '<p>Магазин ' . config ('app.name') . ' пропонує оригінальні запчастини та копії високої якості до смартфону Lenovo A316 оптом і в роздріб.</p>',
            ],
            [
                'url' => 'Lenovo/a319',
                'breadcrumb' => 'a319',
                'image' => null,
                'title' => 'A319',
                'page_title_en' => 'Spare parts for smartphones Lenovo A319',
                'page_title_ru' => 'Запчасти к смартфонам Lenovo A319',
                'page_title_ua' => 'Запчастини до смартфонів Lenovo A319',
                'meta_title_en' => 'Spare parts for smartphones Lenovo A319 ' . $wholesaleRetail_en,
                'meta_title_ru' => 'Запчасти к смартфонам Lenovo A319 ' . $wholesaleRetail_ru,
                'meta_title_ua' => 'Запчастини до смартфонів Lenovo A319 ' . $wholesaleRetail_ua,
                'meta_description_en' => 'Spare parts for smartphones Lenovo A319. ' . ucfirst($wholesaleRetail_en). ', ' . $originalCopy_en . '. ' . ucfirst($features_en) . ' &#8212; ' . $bue_en,
                'meta_description_ru' => 'Запчасти к смартфонам Lenovo A319. ' . ucfirst($wholesaleRetail_ru). ', ' . $originalCopy_ru . '. ' . ucfirst($features_ru) . ' &#8212; ' . $bue_ru,
                'meta_description_ua' => 'Запчастини до смартфонів Lenovo A319. ' . ucfirst($wholesaleRetail_ua). ', ' . $originalCopy_ua . '. ' . ucfirst($features_ua) . ' &#8212; ' . $bue_ua,
                'meta_keywords_en' => 'Lenovo A319',
                'meta_keywords_ru' => 'Lenovo A319',
                'meta_keywords_ua' => 'Lenovo A319',
                'summary_en' => '<p>' . config ('app.name'). ' shop offers original spare parts and high quality copies for the Lenovo A319 smartphone wholesale and retail.</p>',
                'summary_ru' => '<p>Магазин '. config ( 'app.name'). ' предлагает оригинальные запчасти и копии высокого качества к смартфону Lenovo A319 оптом и в розницу.</p>',
                'summary_ua' => '<p>Магазин ' . config ('app.name') . ' пропонує оригінальні запчастини та копії високої якості до смартфону Lenovo A319 оптом і в роздріб.</p>',
            ],
            [
                'url' => 'Lenovo/a396',
                'breadcrumb' => 'a396',
                'image' => null,
                'title' => 'A396',
                'page_title_en' => 'Spare parts for smartphones Lenovo A396',
                'page_title_ru' => 'Запчасти к смартфонам Lenovo A396',
                'page_title_ua' => 'Запчастини до смартфонів Lenovo A396',
                'meta_title_en' => 'Spare parts for smartphones Lenovo A396 ' . $wholesaleRetail_en,
                'meta_title_ru' => 'Запчасти к смартфонам Lenovo A396 ' . $wholesaleRetail_ru,
                'meta_title_ua' => 'Запчастини до смартфонів Lenovo A396 ' . $wholesaleRetail_ua,
                'meta_description_en' => 'Spare parts for smartphones Lenovo A396. ' . ucfirst($wholesaleRetail_en). ', ' . $originalCopy_en . '. ' . ucfirst($features_en) . ' &#8212; ' . $bue_en,
                'meta_description_ru' => 'Запчасти к смартфонам Lenovo A396. ' . ucfirst($wholesaleRetail_ru). ', ' . $originalCopy_ru . '. ' . ucfirst($features_ru) . ' &#8212; ' . $bue_ru,
                'meta_description_ua' => 'Запчастини до смартфонів Lenovo A396. ' . ucfirst($wholesaleRetail_ua). ', ' . $originalCopy_ua . '. ' . ucfirst($features_ua) . ' &#8212; ' . $bue_ua,
                'meta_keywords_en' => 'Lenovo A396',
                'meta_keywords_ru' => 'Lenovo A396',
                'meta_keywords_ua' => 'Lenovo A396',
                'summary_en' => '<p>' . config ('app.name'). ' shop offers original spare parts and high quality copies for the Lenovo A396 smartphone wholesale and retail.</p>',
                'summary_ru' => '<p>Магазин '. config ( 'app.name'). ' предлагает оригинальные запчасти и копии высокого качества к смартфону Lenovo A396 оптом и в розницу.</p>',
                'summary_ua' => '<p>Магазин ' . config ('app.name') . ' пропонує оригінальні запчастини та копії високої якості до смартфону Lenovo A396 оптом і в роздріб.</p>',
            ],
            [
                'url' => 'Lenovo/a690',
                'breadcrumb' => 'a690',
                'image' => null,
                'title' => 'A690',
                'page_title_en' => 'Spare parts for smartphones Lenovo A690',
                'page_title_ru' => 'Запчасти к смартфонам Lenovo A690',
                'page_title_ua' => 'Запчастини до смартфонів Lenovo A690',
                'meta_title_en' => 'Spare parts for smartphones Lenovo A690 ' . $wholesaleRetail_en,
                'meta_title_ru' => 'Запчасти к смартфонам Lenovo A690 ' . $wholesaleRetail_ru,
                'meta_title_ua' => 'Запчастини до смартфонів Lenovo A690 ' . $wholesaleRetail_ua,
                'meta_description_en' => 'Spare parts for smartphones Lenovo A690. ' . ucfirst($wholesaleRetail_en). ', ' . $originalCopy_en . '. ' . ucfirst($features_en) . ' &#8212; ' . $bue_en,
                'meta_description_ru' => 'Запчасти к смартфонам Lenovo A690. ' . ucfirst($wholesaleRetail_ru). ', ' . $originalCopy_ru . '. ' . ucfirst($features_ru) . ' &#8212; ' . $bue_ru,
                'meta_description_ua' => 'Запчастини до смартфонів Lenovo A690. ' . ucfirst($wholesaleRetail_ua). ', ' . $originalCopy_ua . '. ' . ucfirst($features_ua) . ' &#8212; ' . $bue_ua,
                'meta_keywords_en' => 'Lenovo A690',
                'meta_keywords_ru' => 'Lenovo A690',
                'meta_keywords_ua' => 'Lenovo A690',
                'summary_en' => '<p>' . config ('app.name'). ' shop offers original spare parts and high quality copies for the Lenovo A690 smartphone wholesale and retail.</p>',
                'summary_ru' => '<p>Магазин '. config ( 'app.name'). ' предлагает оригинальные запчасти и копии высокого качества к смартфону Lenovo A690 оптом и в розницу.</p>',
                'summary_ua' => '<p>Магазин ' . config ('app.name') . ' пропонує оригінальні запчастини та копії високої якості до смартфону Lenovo A690 оптом і в роздріб.</p>',
            ],
            [
                'url' => 'Lenovo/a5000',
                'breadcrumb' => 'a5000',
                'image' => null,
                'title' => 'A5000',
                'page_title_en' => 'Spare parts for smartphones Lenovo A5000',
                'page_title_ru' => 'Запчасти к смартфонам Lenovo A5000',
                'page_title_ua' => 'Запчастини до смартфонів Lenovo A5000',
                'meta_title_en' => 'Spare parts for smartphones Lenovo A5000 ' . $wholesaleRetail_en,
                'meta_title_ru' => 'Запчасти к смартфонам Lenovo A5000 ' . $wholesaleRetail_ru,
                'meta_title_ua' => 'Запчастини до смартфонів Lenovo A5000 ' . $wholesaleRetail_ua,
                'meta_description_en' => 'Spare parts for smartphones Lenovo A5000. ' . ucfirst($wholesaleRetail_en). ', ' . $originalCopy_en . '. ' . ucfirst($features_en) . ' &#8212; ' . $bue_en,
                'meta_description_ru' => 'Запчасти к смартфонам Lenovo A5000. ' . ucfirst($wholesaleRetail_ru). ', ' . $originalCopy_ru . '. ' . ucfirst($features_ru) . ' &#8212; ' . $bue_ru,
                'meta_description_ua' => 'Запчастини до смартфонів Lenovo A5000. ' . ucfirst($wholesaleRetail_ua). ', ' . $originalCopy_ua . '. ' . ucfirst($features_ua) . ' &#8212; ' . $bue_ua,
                'meta_keywords_en' => 'Lenovo A5000',
                'meta_keywords_ru' => 'Lenovo A5000',
                'meta_keywords_ua' => 'Lenovo A5000',
                'summary_en' => '<p>' . config ('app.name'). ' shop offers original spare parts and high quality copies for the Lenovo A5000 smartphone wholesale and retail.</p>',
                'summary_ru' => '<p>Магазин '. config ( 'app.name'). ' предлагает оригинальные запчасти и копии высокого качества к смартфону Lenovo A5000 оптом и в розницу.</p>',
                'summary_ua' => '<p>Магазин ' . config ('app.name') . ' пропонує оригінальні запчастини та копії високої якості до смартфону Lenovo A5000 оптом і в роздріб.</p>',
            ],
        ],
    ],
];